"""Minimal sounddevice stubs used by this project."""

from __future__ import annotations

from typing import Any

class OutputStream:
    """Subset of sounddevice.OutputStream used by the service."""

    def __init__(self, *, samplerate: int, channels: int, dtype: str) -> None: ...
    def __enter__(self) -> OutputStream: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> bool | None: ...
    def start(self) -> object: ...
    def stop(self) -> object: ...
    def close(self) -> object: ...
    def write(self, data: Any) -> object: ...
